auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: www.zhiying678.com
url: http://www.zhiying678.com
feed: /atom.xml
author_info: <a href="http://www.zhiying678.com/">zhiying678</a>
